#############################################################################
# Makefile for building: dsremote
# Generated by qmake (3.1) (Qt 5.15.8)
# Project:  dsremote.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile dsremote.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -Wall -Wextra -Wshadow -Wformat-nonliteral -Wformat-security -Wtype-limits -Wfatal-errors -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -Wextra -Wshadow -Wformat -Wformat-nonliteral -Wformat-security -Wtype-limits -Wfatal-errors -Wdeprecated-declarations -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -Imoc -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = dsremote1.0.0
DISTDIR = /home/ramzes/ws/soft/DSRemote/objects/dsremote1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Network.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = objects/

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		about_dialog.cpp \
		utils.c \
		connection.cpp \
		tmc_dev.c \
		tmc_lan.c \
		tled.cpp \
		edflib.c \
		signalcurve.cpp \
		settings_dialog.cpp \
		screen_thread.cpp \
		lan_connect_thread.cpp \
		read_settings_thread.cpp \
		save_data_thread.cpp \
		decode_dialog.cpp \
		tdial.cpp \
		wave_dialog.cpp \
		wave_view.cpp \
		playback_dialog.cpp \
		third_party/kiss_fft/kiss_fft.c \
		third_party/kiss_fft/kiss_fftr.c qrc_images.cpp \
		moc/moc_mainwindow.cpp \
		moc/moc_about_dialog.cpp \
		moc/moc_tled.cpp \
		moc/moc_signalcurve.cpp \
		moc/moc_settings_dialog.cpp \
		moc/moc_screen_thread.cpp \
		moc/moc_lan_connect_thread.cpp \
		moc/moc_read_settings_thread.cpp \
		moc/moc_save_data_thread.cpp \
		moc/moc_decode_dialog.cpp \
		moc/moc_tdial.cpp \
		moc/moc_wave_dialog.cpp \
		moc/moc_wave_view.cpp \
		moc/moc_playback_dialog.cpp
OBJECTS       = objects/main.o \
		objects/mainwindow.o \
		objects/about_dialog.o \
		objects/utils.o \
		objects/connection.o \
		objects/tmc_dev.o \
		objects/tmc_lan.o \
		objects/tled.o \
		objects/edflib.o \
		objects/signalcurve.o \
		objects/settings_dialog.o \
		objects/screen_thread.o \
		objects/lan_connect_thread.o \
		objects/read_settings_thread.o \
		objects/save_data_thread.o \
		objects/decode_dialog.o \
		objects/tdial.o \
		objects/wave_dialog.o \
		objects/wave_view.o \
		objects/playback_dialog.o \
		objects/kiss_fft.o \
		objects/kiss_fftr.o \
		objects/qrc_images.o \
		objects/moc_mainwindow.o \
		objects/moc_about_dialog.o \
		objects/moc_tled.o \
		objects/moc_signalcurve.o \
		objects/moc_settings_dialog.o \
		objects/moc_screen_thread.o \
		objects/moc_lan_connect_thread.o \
		objects/moc_read_settings_thread.o \
		objects/moc_save_data_thread.o \
		objects/moc_decode_dialog.o \
		objects/moc_tdial.o \
		objects/moc_wave_dialog.o \
		objects/moc_wave_view.o \
		objects/moc_playback_dialog.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KService.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/largefile.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		dsremote.pro qt_headers.h \
		global.h \
		mainwindow.h \
		about_dialog.h \
		utils.h \
		connection.h \
		tmc_dev.h \
		tmc_lan.h \
		tled.h \
		edflib.h \
		signalcurve.h \
		settings_dialog.h \
		screen_thread.h \
		lan_connect_thread.h \
		read_settings_thread.h \
		save_data_thread.h \
		decode_dialog.h \
		tdial.h \
		wave_dialog.h \
		wave_view.h \
		playback_dialog.h \
		third_party/kiss_fft/kiss_fft.h \
		third_party/kiss_fft/_kiss_fft_guts.h \
		third_party/kiss_fft/kiss_fftr.h main.cpp \
		mainwindow.cpp \
		about_dialog.cpp \
		utils.c \
		connection.cpp \
		tmc_dev.c \
		tmc_lan.c \
		tled.cpp \
		edflib.c \
		signalcurve.cpp \
		settings_dialog.cpp \
		screen_thread.cpp \
		lan_connect_thread.cpp \
		read_settings_thread.cpp \
		save_data_thread.cpp \
		decode_dialog.cpp \
		tdial.cpp \
		wave_dialog.cpp \
		wave_view.cpp \
		playback_dialog.cpp \
		third_party/kiss_fft/kiss_fft.c \
		third_party/kiss_fft/kiss_fftr.c
QMAKE_TARGET  = dsremote
DESTDIR       = 
TARGET        = dsremote


first: all
####### Build rules

dsremote:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: dsremote.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KService.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/largefile.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		dsremote.pro \
		images.qrc
	$(QMAKE) -o Makefile dsremote.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigCore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigGui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCoreAddons.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDBusAddons.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KI18n.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KService.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWindowSystem.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/largefile.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
dsremote.pro:
images.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile dsremote.pro

qmake_all: FORCE


all: Makefile dsremote

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents images.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents qt_headers.h global.h mainwindow.h about_dialog.h utils.h connection.h tmc_dev.h tmc_lan.h tled.h edflib.h signalcurve.h settings_dialog.h screen_thread.h lan_connect_thread.h read_settings_thread.h save_data_thread.h decode_dialog.h tdial.h wave_dialog.h wave_view.h playback_dialog.h third_party/kiss_fft/kiss_fft.h third_party/kiss_fft/_kiss_fft_guts.h third_party/kiss_fft/kiss_fftr.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp about_dialog.cpp utils.c connection.cpp tmc_dev.c tmc_lan.c tled.cpp edflib.c signalcurve.cpp settings_dialog.cpp screen_thread.cpp lan_connect_thread.cpp read_settings_thread.cpp save_data_thread.cpp decode_dialog.cpp tdial.cpp wave_dialog.cpp wave_view.cpp playback_dialog.cpp third_party/kiss_fft/kiss_fft.c third_party/kiss_fft/kiss_fftr.c $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_images.cpp
qrc_images.cpp: images.qrc \
		/usr/lib/qt5/bin/rcc \
		images/stop.png \
		images/playpause.png \
		images/record.png \
		images/r_dsremote.png
	/usr/lib/qt5/bin/rcc -name images images.qrc -o qrc_images.cpp

compiler_moc_predefs_make_all: moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc/moc_predefs.h
moc/moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -Wextra -Wshadow -Wformat -Wformat-nonliteral -Wformat-security -Wtype-limits -Wfatal-errors -Wdeprecated-declarations -O2 -Wall -Wextra -dM -E -o moc/moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc/moc_mainwindow.cpp moc/moc_about_dialog.cpp moc/moc_tled.cpp moc/moc_signalcurve.cpp moc/moc_settings_dialog.cpp moc/moc_screen_thread.cpp moc/moc_lan_connect_thread.cpp moc/moc_read_settings_thread.cpp moc/moc_save_data_thread.cpp moc/moc_decode_dialog.cpp moc/moc_tdial.cpp moc/moc_wave_dialog.cpp moc/moc_wave_view.cpp moc/moc_playback_dialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_mainwindow.cpp moc/moc_about_dialog.cpp moc/moc_tled.cpp moc/moc_signalcurve.cpp moc/moc_settings_dialog.cpp moc/moc_screen_thread.cpp moc/moc_lan_connect_thread.cpp moc/moc_read_settings_thread.cpp moc/moc_save_data_thread.cpp moc/moc_decode_dialog.cpp moc/moc_tdial.cpp moc/moc_wave_dialog.cpp moc/moc_wave_view.cpp moc/moc_playback_dialog.cpp
moc/moc_mainwindow.cpp: mainwindow.h \
		qt_headers.h \
		global.h \
		third_party/kiss_fft/kiss_fftr.h \
		third_party/kiss_fft/kiss_fft.h \
		about_dialog.h \
		mainwindow.h \
		utils.h \
		connection.h \
		tmc_dev.h \
		tmc_lan.h \
		tled.h \
		edflib.h \
		signalcurve.h \
		settings_dialog.h \
		screen_thread.h \
		lan_connect_thread.h \
		read_settings_thread.h \
		save_data_thread.h \
		decode_dialog.h \
		tdial.h \
		wave_dialog.h \
		wave_view.h \
		playback_dialog.h \
		moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ramzes/ws/soft/DSRemote/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ramzes/ws/soft/DSRemote -I/home/ramzes/ws/soft/DSRemote -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/x86_64-linux-gnu/include -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc/moc_mainwindow.cpp

moc/moc_about_dialog.cpp: about_dialog.h \
		global.h \
		third_party/kiss_fft/kiss_fftr.h \
		third_party/kiss_fft/kiss_fft.h \
		mainwindow.h \
		qt_headers.h \
		about_dialog.h \
		utils.h \
		connection.h \
		tmc_dev.h \
		tmc_lan.h \
		tled.h \
		edflib.h \
		signalcurve.h \
		settings_dialog.h \
		screen_thread.h \
		lan_connect_thread.h \
		read_settings_thread.h \
		save_data_thread.h \
		decode_dialog.h \
		tdial.h \
		wave_dialog.h \
		wave_view.h \
		playback_dialog.h \
		moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ramzes/ws/soft/DSRemote/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ramzes/ws/soft/DSRemote -I/home/ramzes/ws/soft/DSRemote -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/x86_64-linux-gnu/include -I/usr/include/x86_64-linux-gnu -I/usr/include about_dialog.h -o moc/moc_about_dialog.cpp

moc/moc_tled.cpp: tled.h \
		moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ramzes/ws/soft/DSRemote/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ramzes/ws/soft/DSRemote -I/home/ramzes/ws/soft/DSRemote -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/x86_64-linux-gnu/include -I/usr/include/x86_64-linux-gnu -I/usr/include tled.h -o moc/moc_tled.cpp

moc/moc_signalcurve.cpp: signalcurve.h \
		mainwindow.h \
		qt_headers.h \
		global.h \
		third_party/kiss_fft/kiss_fftr.h \
		third_party/kiss_fft/kiss_fft.h \
		about_dialog.h \
		utils.h \
		connection.h \
		tmc_dev.h \
		tmc_lan.h \
		tled.h \
		edflib.h \
		signalcurve.h \
		settings_dialog.h \
		screen_thread.h \
		lan_connect_thread.h \
		read_settings_thread.h \
		save_data_thread.h \
		decode_dialog.h \
		tdial.h \
		wave_dialog.h \
		wave_view.h \
		playback_dialog.h \
		moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ramzes/ws/soft/DSRemote/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ramzes/ws/soft/DSRemote -I/home/ramzes/ws/soft/DSRemote -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/x86_64-linux-gnu/include -I/usr/include/x86_64-linux-gnu -I/usr/include signalcurve.h -o moc/moc_signalcurve.cpp

moc/moc_settings_dialog.cpp: settings_dialog.h \
		qt_headers.h \
		mainwindow.h \
		global.h \
		third_party/kiss_fft/kiss_fftr.h \
		third_party/kiss_fft/kiss_fft.h \
		about_dialog.h \
		utils.h \
		connection.h \
		tmc_dev.h \
		tmc_lan.h \
		tled.h \
		edflib.h \
		signalcurve.h \
		settings_dialog.h \
		screen_thread.h \
		lan_connect_thread.h \
		read_settings_thread.h \
		save_data_thread.h \
		decode_dialog.h \
		tdial.h \
		wave_dialog.h \
		wave_view.h \
		playback_dialog.h \
		moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ramzes/ws/soft/DSRemote/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ramzes/ws/soft/DSRemote -I/home/ramzes/ws/soft/DSRemote -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/x86_64-linux-gnu/include -I/usr/include/x86_64-linux-gnu -I/usr/include settings_dialog.h -o moc/moc_settings_dialog.cpp

moc/moc_screen_thread.cpp: screen_thread.h \
		global.h \
		third_party/kiss_fft/kiss_fftr.h \
		third_party/kiss_fft/kiss_fft.h \
		utils.h \
		connection.h \
		tmc_dev.h \
		tmc_lan.h \
		moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ramzes/ws/soft/DSRemote/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ramzes/ws/soft/DSRemote -I/home/ramzes/ws/soft/DSRemote -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/x86_64-linux-gnu/include -I/usr/include/x86_64-linux-gnu -I/usr/include screen_thread.h -o moc/moc_screen_thread.cpp

moc/moc_lan_connect_thread.cpp: lan_connect_thread.h \
		global.h \
		third_party/kiss_fft/kiss_fftr.h \
		third_party/kiss_fft/kiss_fft.h \
		utils.h \
		connection.h \
		tmc_dev.h \
		tmc_lan.h \
		moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ramzes/ws/soft/DSRemote/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ramzes/ws/soft/DSRemote -I/home/ramzes/ws/soft/DSRemote -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/x86_64-linux-gnu/include -I/usr/include/x86_64-linux-gnu -I/usr/include lan_connect_thread.h -o moc/moc_lan_connect_thread.cpp

moc/moc_read_settings_thread.cpp: read_settings_thread.h \
		global.h \
		third_party/kiss_fft/kiss_fftr.h \
		third_party/kiss_fft/kiss_fft.h \
		utils.h \
		connection.h \
		tmc_dev.h \
		tmc_lan.h \
		moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ramzes/ws/soft/DSRemote/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ramzes/ws/soft/DSRemote -I/home/ramzes/ws/soft/DSRemote -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/x86_64-linux-gnu/include -I/usr/include/x86_64-linux-gnu -I/usr/include read_settings_thread.h -o moc/moc_read_settings_thread.cpp

moc/moc_save_data_thread.cpp: save_data_thread.h \
		global.h \
		third_party/kiss_fft/kiss_fftr.h \
		third_party/kiss_fft/kiss_fft.h \
		utils.h \
		connection.h \
		tmc_dev.h \
		tmc_lan.h \
		edflib.h \
		moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ramzes/ws/soft/DSRemote/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ramzes/ws/soft/DSRemote -I/home/ramzes/ws/soft/DSRemote -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/x86_64-linux-gnu/include -I/usr/include/x86_64-linux-gnu -I/usr/include save_data_thread.h -o moc/moc_save_data_thread.cpp

moc/moc_decode_dialog.cpp: decode_dialog.h \
		qt_headers.h \
		global.h \
		third_party/kiss_fft/kiss_fftr.h \
		third_party/kiss_fft/kiss_fft.h \
		mainwindow.h \
		about_dialog.h \
		utils.h \
		connection.h \
		tmc_dev.h \
		tmc_lan.h \
		tled.h \
		edflib.h \
		signalcurve.h \
		settings_dialog.h \
		screen_thread.h \
		lan_connect_thread.h \
		read_settings_thread.h \
		save_data_thread.h \
		decode_dialog.h \
		tdial.h \
		wave_dialog.h \
		wave_view.h \
		playback_dialog.h \
		moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ramzes/ws/soft/DSRemote/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ramzes/ws/soft/DSRemote -I/home/ramzes/ws/soft/DSRemote -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/x86_64-linux-gnu/include -I/usr/include/x86_64-linux-gnu -I/usr/include decode_dialog.h -o moc/moc_decode_dialog.cpp

moc/moc_tdial.cpp: tdial.h \
		moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ramzes/ws/soft/DSRemote/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ramzes/ws/soft/DSRemote -I/home/ramzes/ws/soft/DSRemote -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/x86_64-linux-gnu/include -I/usr/include/x86_64-linux-gnu -I/usr/include tdial.h -o moc/moc_tdial.cpp

moc/moc_wave_dialog.cpp: wave_dialog.h \
		qt_headers.h \
		mainwindow.h \
		global.h \
		third_party/kiss_fft/kiss_fftr.h \
		third_party/kiss_fft/kiss_fft.h \
		about_dialog.h \
		utils.h \
		connection.h \
		tmc_dev.h \
		tmc_lan.h \
		tled.h \
		edflib.h \
		signalcurve.h \
		settings_dialog.h \
		screen_thread.h \
		lan_connect_thread.h \
		read_settings_thread.h \
		save_data_thread.h \
		decode_dialog.h \
		tdial.h \
		wave_dialog.h \
		wave_view.h \
		playback_dialog.h \
		moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ramzes/ws/soft/DSRemote/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ramzes/ws/soft/DSRemote -I/home/ramzes/ws/soft/DSRemote -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/x86_64-linux-gnu/include -I/usr/include/x86_64-linux-gnu -I/usr/include wave_dialog.h -o moc/moc_wave_dialog.cpp

moc/moc_wave_view.cpp: wave_view.h \
		qt_headers.h \
		global.h \
		third_party/kiss_fft/kiss_fftr.h \
		third_party/kiss_fft/kiss_fft.h \
		utils.h \
		wave_dialog.h \
		mainwindow.h \
		about_dialog.h \
		connection.h \
		tmc_dev.h \
		tmc_lan.h \
		tled.h \
		edflib.h \
		signalcurve.h \
		settings_dialog.h \
		screen_thread.h \
		lan_connect_thread.h \
		read_settings_thread.h \
		save_data_thread.h \
		decode_dialog.h \
		tdial.h \
		playback_dialog.h \
		wave_view.h \
		moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ramzes/ws/soft/DSRemote/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ramzes/ws/soft/DSRemote -I/home/ramzes/ws/soft/DSRemote -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/x86_64-linux-gnu/include -I/usr/include/x86_64-linux-gnu -I/usr/include wave_view.h -o moc/moc_wave_view.cpp

moc/moc_playback_dialog.cpp: playback_dialog.h \
		qt_headers.h \
		global.h \
		third_party/kiss_fft/kiss_fftr.h \
		third_party/kiss_fft/kiss_fft.h \
		mainwindow.h \
		about_dialog.h \
		utils.h \
		connection.h \
		tmc_dev.h \
		tmc_lan.h \
		tled.h \
		edflib.h \
		signalcurve.h \
		settings_dialog.h \
		screen_thread.h \
		lan_connect_thread.h \
		read_settings_thread.h \
		save_data_thread.h \
		decode_dialog.h \
		tdial.h \
		wave_dialog.h \
		wave_view.h \
		playback_dialog.h \
		moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/ramzes/ws/soft/DSRemote/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/ramzes/ws/soft/DSRemote -I/home/ramzes/ws/soft/DSRemote -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/x86_64-linux-gnu/include -I/usr/include/x86_64-linux-gnu -I/usr/include playback_dialog.h -o moc/moc_playback_dialog.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

objects/main.o: main.cpp mainwindow.h \
		qt_headers.h \
		global.h \
		third_party/kiss_fft/kiss_fftr.h \
		third_party/kiss_fft/kiss_fft.h \
		about_dialog.h \
		utils.h \
		connection.h \
		tmc_dev.h \
		tmc_lan.h \
		tled.h \
		edflib.h \
		signalcurve.h \
		settings_dialog.h \
		screen_thread.h \
		lan_connect_thread.h \
		read_settings_thread.h \
		save_data_thread.h \
		decode_dialog.h \
		tdial.h \
		wave_dialog.h \
		wave_view.h \
		playback_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/main.o main.cpp

objects/mainwindow.o: mainwindow.cpp mainwindow.h \
		qt_headers.h \
		global.h \
		third_party/kiss_fft/kiss_fftr.h \
		third_party/kiss_fft/kiss_fft.h \
		about_dialog.h \
		utils.h \
		connection.h \
		tmc_dev.h \
		tmc_lan.h \
		tled.h \
		edflib.h \
		signalcurve.h \
		settings_dialog.h \
		screen_thread.h \
		lan_connect_thread.h \
		read_settings_thread.h \
		save_data_thread.h \
		decode_dialog.h \
		tdial.h \
		wave_dialog.h \
		wave_view.h \
		playback_dialog.h \
		mainwindow_constr.cpp \
		timer_handlers.cpp \
		save_data.cpp \
		interface.cpp \
		serial_decoder.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/mainwindow.o mainwindow.cpp

objects/about_dialog.o: about_dialog.cpp about_dialog.h \
		global.h \
		third_party/kiss_fft/kiss_fftr.h \
		third_party/kiss_fft/kiss_fft.h \
		mainwindow.h \
		qt_headers.h \
		utils.h \
		connection.h \
		tmc_dev.h \
		tmc_lan.h \
		tled.h \
		edflib.h \
		signalcurve.h \
		settings_dialog.h \
		screen_thread.h \
		lan_connect_thread.h \
		read_settings_thread.h \
		save_data_thread.h \
		decode_dialog.h \
		tdial.h \
		wave_dialog.h \
		wave_view.h \
		playback_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/about_dialog.o about_dialog.cpp

objects/utils.o: utils.c utils.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o objects/utils.o utils.c

objects/connection.o: connection.cpp connection.h \
		global.h \
		third_party/kiss_fft/kiss_fftr.h \
		third_party/kiss_fft/kiss_fft.h \
		tmc_dev.h \
		tmc_lan.h \
		utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/connection.o connection.cpp

objects/tmc_dev.o: tmc_dev.c tmc_dev.h \
		utils.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o objects/tmc_dev.o tmc_dev.c

objects/tmc_lan.o: tmc_lan.c tmc_dev.h \
		utils.h \
		tmc_lan.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o objects/tmc_lan.o tmc_lan.c

objects/tled.o: tled.cpp tled.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/tled.o tled.cpp

objects/edflib.o: edflib.c edflib.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o objects/edflib.o edflib.c

objects/signalcurve.o: signalcurve.cpp signalcurve.h \
		mainwindow.h \
		qt_headers.h \
		global.h \
		third_party/kiss_fft/kiss_fftr.h \
		third_party/kiss_fft/kiss_fft.h \
		about_dialog.h \
		utils.h \
		connection.h \
		tmc_dev.h \
		tmc_lan.h \
		tled.h \
		edflib.h \
		settings_dialog.h \
		screen_thread.h \
		lan_connect_thread.h \
		read_settings_thread.h \
		save_data_thread.h \
		decode_dialog.h \
		tdial.h \
		wave_dialog.h \
		wave_view.h \
		playback_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/signalcurve.o signalcurve.cpp

objects/settings_dialog.o: settings_dialog.cpp settings_dialog.h \
		qt_headers.h \
		mainwindow.h \
		global.h \
		third_party/kiss_fft/kiss_fftr.h \
		third_party/kiss_fft/kiss_fft.h \
		about_dialog.h \
		utils.h \
		connection.h \
		tmc_dev.h \
		tmc_lan.h \
		tled.h \
		edflib.h \
		signalcurve.h \
		screen_thread.h \
		lan_connect_thread.h \
		read_settings_thread.h \
		save_data_thread.h \
		decode_dialog.h \
		tdial.h \
		wave_dialog.h \
		wave_view.h \
		playback_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/settings_dialog.o settings_dialog.cpp

objects/screen_thread.o: screen_thread.cpp screen_thread.h \
		global.h \
		third_party/kiss_fft/kiss_fftr.h \
		third_party/kiss_fft/kiss_fft.h \
		utils.h \
		connection.h \
		tmc_dev.h \
		tmc_lan.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/screen_thread.o screen_thread.cpp

objects/lan_connect_thread.o: lan_connect_thread.cpp lan_connect_thread.h \
		global.h \
		third_party/kiss_fft/kiss_fftr.h \
		third_party/kiss_fft/kiss_fft.h \
		utils.h \
		connection.h \
		tmc_dev.h \
		tmc_lan.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/lan_connect_thread.o lan_connect_thread.cpp

objects/read_settings_thread.o: read_settings_thread.cpp read_settings_thread.h \
		global.h \
		third_party/kiss_fft/kiss_fftr.h \
		third_party/kiss_fft/kiss_fft.h \
		utils.h \
		connection.h \
		tmc_dev.h \
		tmc_lan.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/read_settings_thread.o read_settings_thread.cpp

objects/save_data_thread.o: save_data_thread.cpp save_data_thread.h \
		global.h \
		third_party/kiss_fft/kiss_fftr.h \
		third_party/kiss_fft/kiss_fft.h \
		utils.h \
		connection.h \
		tmc_dev.h \
		tmc_lan.h \
		edflib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/save_data_thread.o save_data_thread.cpp

objects/decode_dialog.o: decode_dialog.cpp decode_dialog.h \
		qt_headers.h \
		global.h \
		third_party/kiss_fft/kiss_fftr.h \
		third_party/kiss_fft/kiss_fft.h \
		mainwindow.h \
		about_dialog.h \
		utils.h \
		connection.h \
		tmc_dev.h \
		tmc_lan.h \
		tled.h \
		edflib.h \
		signalcurve.h \
		settings_dialog.h \
		screen_thread.h \
		lan_connect_thread.h \
		read_settings_thread.h \
		save_data_thread.h \
		tdial.h \
		wave_dialog.h \
		wave_view.h \
		playback_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/decode_dialog.o decode_dialog.cpp

objects/tdial.o: tdial.cpp tdial.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/tdial.o tdial.cpp

objects/wave_dialog.o: wave_dialog.cpp wave_dialog.h \
		qt_headers.h \
		mainwindow.h \
		global.h \
		third_party/kiss_fft/kiss_fftr.h \
		third_party/kiss_fft/kiss_fft.h \
		about_dialog.h \
		utils.h \
		connection.h \
		tmc_dev.h \
		tmc_lan.h \
		tled.h \
		edflib.h \
		signalcurve.h \
		settings_dialog.h \
		screen_thread.h \
		lan_connect_thread.h \
		read_settings_thread.h \
		save_data_thread.h \
		decode_dialog.h \
		tdial.h \
		playback_dialog.h \
		wave_view.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/wave_dialog.o wave_dialog.cpp

objects/wave_view.o: wave_view.cpp wave_view.h \
		qt_headers.h \
		global.h \
		third_party/kiss_fft/kiss_fftr.h \
		third_party/kiss_fft/kiss_fft.h \
		utils.h \
		wave_dialog.h \
		mainwindow.h \
		about_dialog.h \
		connection.h \
		tmc_dev.h \
		tmc_lan.h \
		tled.h \
		edflib.h \
		signalcurve.h \
		settings_dialog.h \
		screen_thread.h \
		lan_connect_thread.h \
		read_settings_thread.h \
		save_data_thread.h \
		decode_dialog.h \
		tdial.h \
		playback_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/wave_view.o wave_view.cpp

objects/playback_dialog.o: playback_dialog.cpp playback_dialog.h \
		qt_headers.h \
		global.h \
		third_party/kiss_fft/kiss_fftr.h \
		third_party/kiss_fft/kiss_fft.h \
		mainwindow.h \
		about_dialog.h \
		utils.h \
		connection.h \
		tmc_dev.h \
		tmc_lan.h \
		tled.h \
		edflib.h \
		signalcurve.h \
		settings_dialog.h \
		screen_thread.h \
		lan_connect_thread.h \
		read_settings_thread.h \
		save_data_thread.h \
		decode_dialog.h \
		tdial.h \
		wave_dialog.h \
		wave_view.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/playback_dialog.o playback_dialog.cpp

objects/kiss_fft.o: third_party/kiss_fft/kiss_fft.c third_party/kiss_fft/_kiss_fft_guts.h \
		third_party/kiss_fft/kiss_fft.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o objects/kiss_fft.o third_party/kiss_fft/kiss_fft.c

objects/kiss_fftr.o: third_party/kiss_fft/kiss_fftr.c third_party/kiss_fft/kiss_fftr.h \
		third_party/kiss_fft/kiss_fft.h \
		third_party/kiss_fft/_kiss_fft_guts.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o objects/kiss_fftr.o third_party/kiss_fft/kiss_fftr.c

objects/qrc_images.o: qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/qrc_images.o qrc_images.cpp

objects/moc_mainwindow.o: moc/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_mainwindow.o moc/moc_mainwindow.cpp

objects/moc_about_dialog.o: moc/moc_about_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_about_dialog.o moc/moc_about_dialog.cpp

objects/moc_tled.o: moc/moc_tled.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_tled.o moc/moc_tled.cpp

objects/moc_signalcurve.o: moc/moc_signalcurve.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_signalcurve.o moc/moc_signalcurve.cpp

objects/moc_settings_dialog.o: moc/moc_settings_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_settings_dialog.o moc/moc_settings_dialog.cpp

objects/moc_screen_thread.o: moc/moc_screen_thread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_screen_thread.o moc/moc_screen_thread.cpp

objects/moc_lan_connect_thread.o: moc/moc_lan_connect_thread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_lan_connect_thread.o moc/moc_lan_connect_thread.cpp

objects/moc_read_settings_thread.o: moc/moc_read_settings_thread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_read_settings_thread.o moc/moc_read_settings_thread.cpp

objects/moc_save_data_thread.o: moc/moc_save_data_thread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_save_data_thread.o moc/moc_save_data_thread.cpp

objects/moc_decode_dialog.o: moc/moc_decode_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_decode_dialog.o moc/moc_decode_dialog.cpp

objects/moc_tdial.o: moc/moc_tdial.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_tdial.o moc/moc_tdial.cpp

objects/moc_wave_dialog.o: moc/moc_wave_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_wave_dialog.o moc/moc_wave_dialog.cpp

objects/moc_wave_view.o: moc/moc_wave_view.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_wave_view.o moc/moc_wave_view.cpp

objects/moc_playback_dialog.o: moc/moc_playback_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_playback_dialog.o moc/moc_playback_dialog.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/bin || mkdir -p $(INSTALL_ROOT)/usr/bin
	$(QINSTALL_PROGRAM) /home/ramzes/ws/soft/DSRemote/dsremote $(INSTALL_ROOT)/usr/bin/dsremote

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/bin/dsremote
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/bin/ 


install_icon_a: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/icons || mkdir -p $(INSTALL_ROOT)/usr/share/icons
	$(QINSTALL) /home/ramzes/ws/soft/DSRemote/images/r_dsremote.png $(INSTALL_ROOT)/usr/share/icons/r_dsremote.png

uninstall_icon_a: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/icons/r_dsremote.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/icons/ 


install_icon_b: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/pixmaps || mkdir -p $(INSTALL_ROOT)/usr/share/pixmaps
	$(QINSTALL) /home/ramzes/ws/soft/DSRemote/images/r_dsremote.png $(INSTALL_ROOT)/usr/share/pixmaps/r_dsremote.png

uninstall_icon_b: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/pixmaps/r_dsremote.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/pixmaps/ 


install_icon_c: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/icons/hicolor/48x48/apps || mkdir -p $(INSTALL_ROOT)/usr/share/icons/hicolor/48x48/apps
	$(QINSTALL) /home/ramzes/ws/soft/DSRemote/images/r_dsremote.png $(INSTALL_ROOT)/usr/share/icons/hicolor/48x48/apps/r_dsremote.png

uninstall_icon_c: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/icons/hicolor/48x48/apps/r_dsremote.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/48x48/apps/ 


install_icon_d: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/icons/hicolor/48x48/mimetypes || mkdir -p $(INSTALL_ROOT)/usr/share/icons/hicolor/48x48/mimetypes
	$(QINSTALL) /home/ramzes/ws/soft/DSRemote/images/r_dsremote.png $(INSTALL_ROOT)/usr/share/icons/hicolor/48x48/mimetypes/r_dsremote.png

uninstall_icon_d: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/icons/hicolor/48x48/mimetypes/r_dsremote.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/48x48/mimetypes/ 


install_desktop_link: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/applications || mkdir -p $(INSTALL_ROOT)/usr/share/applications
	$(QINSTALL) /home/ramzes/ws/soft/DSRemote/install/dsremote.desktop $(INSTALL_ROOT)/usr/share/applications/dsremote.desktop

uninstall_desktop_link: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/applications/dsremote.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/applications/ 


install_udev_rule: first FORCE
	@test -d $(INSTALL_ROOT)/etc/udev/rules.d || mkdir -p $(INSTALL_ROOT)/etc/udev/rules.d
	$(QINSTALL) /home/ramzes/ws/soft/DSRemote/install/30-usbtmc.rules $(INSTALL_ROOT)/etc/udev/rules.d/30-usbtmc.rules

uninstall_udev_rule: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/etc/udev/rules.d/30-usbtmc.rules
	-$(DEL_DIR) $(INSTALL_ROOT)/etc/udev/rules.d/ 


install: install_target install_icon_a install_icon_b install_icon_c install_icon_d install_desktop_link install_udev_rule  FORCE

uninstall: uninstall_target uninstall_icon_a uninstall_icon_b uninstall_icon_c uninstall_icon_d uninstall_desktop_link uninstall_udev_rule  FORCE

FORCE:

